### PR TITLE
remove nonexisting keys from request and update errorInfo handling

### PR DESCRIPTION
**Pull request by abraxxas**
To be honest i never made a PR on github, so i hope i am not failing terribly here^^ this in reference to the discussion here https://github.com/zeit/next.js/pull/5727

### CODE REVIEW

**Comment by sheerun** [comment]
Looks great, thank you!

**Comment by sheerun** [comment]
@abraxxas Are you sure query is not available? It is logging for me in production and now I don't have access to it in errors. Could you provide an alternative?

**Comment by abraxxas** [comment]
@sheerun Either it is not available or next.js types are not correct or i am having a misunderstanding here. The nextContext we pass to captureException is typed here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/next/index.d.ts and the incomingMessage type it uses for request is defined here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e2988a134ec9fa51deb43487231ac607265ba088/node/index.d.ts#L694 

query is path of the context and not the request. will update the pr

**Comment by abraxxas** [comment]
@sheerun okay had a closer look at this but unfortunately do not have the time to finish this right now. During ssr the request object contains both query and params even though the types say otherwise.  But on the client we could ready query from the context as req/res are not available there.

**Comment by sheerun** [comment]
Ok no problem we're in no hurry

**Pull request merged**
